apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-postgresql-proxy.fullName" . }}
  labels:
    {{- include "nginx-postgresql-proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nginx-postgresql-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-postgresql-proxy.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
          - name: DB_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.databaseConfigMap.name | default (include "nginx-postgresql-proxy.fullName" .) }}
                key: hostname
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.databaseConfigMap.name | default (include "nginx-postgresql-proxy.fullName" .) }}
                key: port
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /var/cache/nginx
            name: cache
          - mountPath: /etc/nginx/conf.d
            name: conf
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: conf
        emptyDir: {}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
